# How to install packages

In [ ]:
package_name = "readxl"
install.packages(package_name)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



# Load the package

In [ ]:
library(package_name)

# BASIC DATA TYPES IN R

In [ ]:
# 1. Numeric
num <- 42
print(paste("Numeric:", num))

# 2. Character
char <- "Hello, World!"
print(paste("Character:", char))

# 3. Logical
log_val <- TRUE
print(paste("Logical:", log_val))

# 4. Complex
comp <- 1 + 2i
print(paste("Complex:", comp))

# 5. Integer
int_val <- 2L
print(paste("Integer:", int_val))



[1] "Numeric: 42"
[1] "Character: Hello, World!"
[1] "Logical: TRUE"
[1] "Complex: 1+2i"
[1] "Integer: 2"


# ARRAYS IN R

In [ ]:
# 1. Vectors (1D array)
vector <- c(1, 2, 3, 4, 5)
vector = c(1, 2, 3, 4, 5)
print("Vector:")
print(vector)

# Accessing elements in a vector
print(paste("Second element of vector:", vector[2]))

# 2. Matrices (2D array)
matrix <- matrix(1:9, nrow=3)
print("Matrix:")
print(matrix)

# Accessing elements in a matrix
print(paste("Element at 2nd row, 3rd column:", matrix[2, 3]))

# 3. Arrays (multi-dimensional)
array_3d <- array(1:24, dim=c(3,4,2))
print("3D Array:")
print(array_3d)

# Accessing elements in a 3D array
print(paste("Element at 2nd row, 1st column, 2nd layer:", array_3d[2, 1, 2]))

# 4. Lists (can contain elements of different types)
list_data <- list(name="John", age=30, scores=c(90, 80, 85))
print("List:")
print(list_data)

# Accessing elements in a list
print(paste("Name from the list:", list_data$name))

# 5. Data frames (tabular data storage)
df <- data.frame(
  Name=c("John", "Jane", "Doe"),
  Age=c(30, 25, 35),
  Score=c(85, 90, 75)
)
print("Data frame:")
print(df)

# Accessing elements in a data frame
print(paste("Score of the second person:", df$Score[2]))


[1] "Vector:"
[1] 1 2 3 4 5
[1] "Second element of vector: 2"
[1] "Matrix:"
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[1] "Element at 2nd row, 3rd column: 8"
[1] "3D Array:"
, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]   13   16   19   22
[2,]   14   17   20   23
[3,]   15   18   21   24

[1] "Element at 2nd row, 1st column, 2nd layer: 14"
[1] "List:"
$name
[1] "John"

$age
[1] 30

$scores
[1] 90 80 85

[1] "Name from the list: John"
[1] "Data frame:"
  Name Age Score
1 John  30    85
2 Jane  25    90
3  Doe  35    75
[1] "Score of the second person: 90"


# Ej 1:   Genera un número aleatorio entre 1 y 1000 y determina si es par o impar. Explica cómo esto se relaciona con los fenómenos aleatorios e incertidumbre.

In [ ]:
set.seed(123) # for reproducibility


num <- sample(1:1000, 1)

if (num %% 2 == 0) {
  print(paste(num, "is even"))
}
else {
  print(paste(num, "is odd"))
}


[1] "415 is odd"
